
services:
  wol-orders:
    container_name: wol-orders
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_JSON_PATH: /app/endpoints
    volumes:
      - ./endpoints:/app/endpoints:ro
    ports:
      - "8000:8000"