
services:
  multi-api:
    container_name: multi-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_JSON_PATH: /app/endpoints
    volumes:
      - ./endpoints:/app/endpoints:ro
    ports:
      - "8000:8000"